version: '3.9'
services:
  app:
    container_name: full_app
    build: .
    ports: 
      - 6667:6667 
    restart: on-failure
    volumes:
      - "/app"
    depends_on:
      - fullstack-postgres
    networks:
      - fullstack


  fullstack-postgres:
    image: postgres:latest
    container_name: postgresq
    environment:
      - POSTGRES_USER=username  
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=mydb
      - DATABASE_HOST=postgresq 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "pgapass"
    depends_on:
      - fullstack-postgres
    ports:
      - "5050:80"
    networks:
      - fullstack
    restart: unless-stopped

volumes:
  api:
  database_postgres:
# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
